# Generated by Django 4.2.4 on 2023-08-11 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_habit_user_habits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='habits',
        ),
        migrations.AddField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('FAILED', 'failed'), ('COMPLETED', 'completed'), ('CHEATED', 'cheated'), ('PENDING', 'pending')], default='PENDING', max_length=9),
        ),
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
    ]
