# Generated by Django 4.2.4 on 2023-08-22 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_habit_name_remove_user_habits_habit_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='status',
        ),
        migrations.AddField(
            model_name='habit',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('FAILED', 'failed'), ('COMPLETED', 'completed'), ('CHEATED', 'cheated'), ('PENDING', 'pending')], default='PENDING', max_length=9)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_entries', to='main.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
