# Generated by Django 4.2.4 on 2023-08-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_habit_status_habit_name_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
