# Generated by Django 4.2.4 on 2023-08-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_habit_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='createdAt',
            field=models.DateField(),
        ),
    ]
